// HelpFix — Supabase Database Types
//
// Bu dosya elle yazıldı; ileride `supabase gen types typescript` ile
// otomatik üretilenle değiştirilebilir. Şimdilik Faz D (Servis Masası)
// için gereken tabloları ve çekirdek (tenant/kullanıcı) tablolarını
// kapsıyor. Yeni modül eklendikçe buraya yeni tablo tipleri eklenecek.

export type Priority = 'P1' | 'P2' | 'P3' | 'P4'
export type TicketStatus =
  | 'new'
  | 'open'
  | 'in_progress'
  | 'on_hold'
  | 'resolved'
  | 'closed'
  | 'merged'
export type TicketChannel = 'portal' | 'email' | 'chat' | 'phone' | 'teams'
export type UserRole = 'tenant_admin' | 'manager' | 'agent' | 'requester'
export type ProblemStatus =
  | 'investigating'
  | 'root_cause_identified'
  | 'known_error'
  | 'monitoring'
  | 'resolved'
  | 'closed'
export type ChangeType = 'standard' | 'normal' | 'emergency'
export type ChangeStatus =
  | 'draft'
  | 'submitted'
  | 'technical_review'
  | 'cab_review'
  | 'approved'
  | 'scheduled'
  | 'in_progress'
  | 'completed'
  | 'failed'
  | 'closed'
export type ApprovalType = 'technical_review' | 'cab'
export type ApprovalStatus = 'pending' | 'approved' | 'rejected'
export type PirOutcome = 'successful' | 'partial' | 'failed' | 'rolled_back'
export type RequestStatus =
  | 'submitted'
  | 'pending_approval'
  | 'approved'
  | 'in_procurement'
  | 'fulfilled'
  | 'rejected'
export type CiType = 'server' | 'laptop' | 'desktop' | 'network_device' | 'software_license' | 'mobile_device' | 'other'
export type CiStatus = 'active' | 'in_repair' | 'retired' | 'unmanaged'
export type CiRelationshipType = 'depends_on' | 'hosted_on' | 'connected_to'
export type ArticleStatus = 'draft' | 'published' | 'archived'

export interface Database {
  public: {
    Tables: {
      tenants: {
        Row: {
          id: string
          name: string
          slug: string
          plan: 'starter' | 'growth' | 'enterprise'
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['tenants']['Row'], 'id' | 'created_at'> & {
          id?: string
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['tenants']['Insert']>
        Relationships: []
      }
      user_profiles: {
        Row: {
          id: string
          tenant_id: string
          auth_user_id: string
          full_name: string
          email: string
          role: UserRole
          department_id: string | null
          avatar_initials: string | null
          is_active: boolean
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['user_profiles']['Row'], 'id' | 'created_at'> & {
          id?: string
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['user_profiles']['Insert']>
        Relationships: []
      }
      departments: {
        Row: {
          id: string
          tenant_id: string
          name: string
          manager_id: string | null
        }
        Insert: Omit<Database['public']['Tables']['departments']['Row'], 'id'> & { id?: string }
        Update: Partial<Database['public']['Tables']['departments']['Insert']>
        Relationships: []
      }
      incidents: {
        Row: {
          id: string
          tenant_id: string
          ref: string // e.g. INC-000418, generated by trigger
          title: string
          description: string | null
          priority: Priority
          status: TicketStatus
          channel: TicketChannel
          category: string | null
          requester_id: string
          assignee_id: string | null
          possible_duplicate_of: string | null
          ci_id: string | null
          sla_policy_id: string | null
          sla_due_at: string | null
          csat_score: number | null
          created_at: string
          updated_at: string
          resolved_at: string | null
          closed_at: string | null
        }
        Insert: Omit<
          Database['public']['Tables']['incidents']['Row'],
          'id' | 'ref' | 'created_at' | 'updated_at'
        > & {
          id?: string
          ref?: string
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['incidents']['Insert']>
        Relationships: []
      }
      incident_comments: {
        Row: {
          id: string
          incident_id: string
          author_id: string
          body: string
          is_internal: boolean
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['incident_comments']['Row'], 'id' | 'created_at'> & {
          id?: string
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['incident_comments']['Insert']>
        Relationships: []
      }
      incident_timeline: {
        Row: {
          id: string
          incident_id: string
          actor_id: string | null
          event_type: string // 'created' | 'assigned' | 'status_changed' | 'ai_action' | ...
          event_data: Record<string, unknown> | null
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['incident_timeline']['Row'], 'id' | 'created_at'> & {
          id?: string
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['incident_timeline']['Insert']>
        Relationships: []
      }
      problems: {
        Row: {
          id: string
          tenant_id: string
          ref: string // e.g. PRB-000031, trigger tarafından üretilir
          title: string
          description: string | null
          status: ProblemStatus
          priority: Priority
          category: string | null
          root_cause: string | null
          is_known_error: boolean
          known_error_workaround: string | null
          owner_id: string | null
          ci_id: string | null
          created_at: string
          updated_at: string
          resolved_at: string | null
        }
        Insert: Omit<
          Database['public']['Tables']['problems']['Row'],
          'id' | 'ref' | 'created_at' | 'updated_at'
        > & {
          id?: string
          ref?: string
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['problems']['Insert']>
        Relationships: []
      }
      problem_incidents: {
        Row: {
          problem_id: string
          incident_id: string
          linked_at: string
        }
        Insert: Omit<Database['public']['Tables']['problem_incidents']['Row'], 'linked_at'> & {
          linked_at?: string
        }
        Update: Partial<Database['public']['Tables']['problem_incidents']['Insert']>
        Relationships: []
      }
      problem_timeline: {
        Row: {
          id: string
          problem_id: string
          actor_id: string | null
          event_type: string
          event_data: Record<string, unknown> | null
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['problem_timeline']['Row'], 'id' | 'created_at'> & {
          id?: string
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['problem_timeline']['Insert']>
        Relationships: []
      }
      changes: {
        Row: {
          id: string
          tenant_id: string
          ref: string // e.g. CHG-000187
          title: string
          description: string | null
          change_type: ChangeType
          status: ChangeStatus
          risk_score: number
          category: string | null
          requester_id: string
          implementer_id: string | null
          scheduled_start: string | null
          scheduled_end: string | null
          actual_start: string | null
          actual_end: string | null
          rollback_plan: string | null
          ci_id: string | null
          pir_outcome: PirOutcome | null
          pir_notes: string | null
          created_at: string
          updated_at: string
          closed_at: string | null
        }
        Insert: Omit<Database['public']['Tables']['changes']['Row'], 'id' | 'ref' | 'created_at' | 'updated_at'> & {
          id?: string
          ref?: string
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['changes']['Insert']>
        Relationships: []
      }
      change_approvals: {
        Row: {
          id: string
          change_id: string
          approval_type: ApprovalType
          approver_id: string | null
          status: ApprovalStatus
          comment: string | null
          decided_at: string | null
        }
        Insert: Omit<Database['public']['Tables']['change_approvals']['Row'], 'id'> & { id?: string }
        Update: Partial<Database['public']['Tables']['change_approvals']['Insert']>
        Relationships: []
      }
      change_timeline: {
        Row: {
          id: string
          change_id: string
          actor_id: string | null
          event_type: string
          event_data: Record<string, unknown> | null
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['change_timeline']['Row'], 'id' | 'created_at'> & {
          id?: string
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['change_timeline']['Insert']>
        Relationships: []
      }
      service_categories: {
        Row: {
          id: string
          tenant_id: string
          name: string
          icon: string | null
          sort_order: number
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['service_categories']['Row'], 'id' | 'created_at'> & {
          id?: string
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['service_categories']['Insert']>
        Relationships: []
      }
      service_catalog_items: {
        Row: {
          id: string
          tenant_id: string
          category_id: string | null
          name: string
          description: string | null
          icon: string | null
          estimated_cost: number | null
          estimated_days: number | null
          requires_approval: boolean
          approval_threshold: number | null
          is_active: boolean
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['service_catalog_items']['Row'], 'id' | 'created_at'> & {
          id?: string
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['service_catalog_items']['Insert']>
        Relationships: []
      }
      service_requests: {
        Row: {
          id: string
          tenant_id: string
          ref: string
          catalog_item_id: string
          requester_id: string
          requested_for_id: string | null
          status: RequestStatus
          notes: string | null
          approver_id: string | null
          approval_comment: string | null
          created_at: string
          updated_at: string
          fulfilled_at: string | null
        }
        Insert: Omit<
          Database['public']['Tables']['service_requests']['Row'],
          'id' | 'ref' | 'created_at' | 'updated_at'
        > & {
          id?: string
          ref?: string
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['service_requests']['Insert']>
        Relationships: []
      }
      configuration_items: {
        Row: {
          id: string
          tenant_id: string
          tag: string
          name: string
          ci_type: CiType
          status: CiStatus
          serial_number: string | null
          assigned_user_id: string | null
          vendor: string | null
          cost: number | null
          purchase_date: string | null
          warranty_expiry: string | null
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: Omit<
          Database['public']['Tables']['configuration_items']['Row'],
          'id' | 'tag' | 'created_at' | 'updated_at'
        > & {
          id?: string
          tag?: string
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['configuration_items']['Insert']>
        Relationships: []
      }
      ci_relationships: {
        Row: {
          id: string
          tenant_id: string
          source_ci_id: string
          target_ci_id: string
          relationship_type: CiRelationshipType
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['ci_relationships']['Row'], 'id' | 'created_at'> & {
          id?: string
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['ci_relationships']['Insert']>
        Relationships: []
      }
      knowledge_articles: {
        Row: {
          id: string
          tenant_id: string
          title: string
          slug: string
          content: string
          category: string | null
          status: ArticleStatus
          author_id: string
          view_count: number
          helpful_count: number
          unhelpful_count: number
          created_at: string
          updated_at: string
          published_at: string | null
        }
        Insert: Omit<
          Database['public']['Tables']['knowledge_articles']['Row'],
          'id' | 'slug' | 'created_at' | 'updated_at' | 'view_count' | 'helpful_count' | 'unhelpful_count'
        > & {
          id?: string
          slug?: string
          created_at?: string
          updated_at?: string
          view_count?: number
          helpful_count?: number
          unhelpful_count?: number
        }
        Update: Partial<Database['public']['Tables']['knowledge_articles']['Insert']>
        Relationships: []
      }
    }
    Views: Record<string, never>
    Functions: {
      get_incident_cluster_candidates: {
        Args: { p_tenant_id: string }
        Returns: {
          category: string
          incident_count: number
          sample_incident_ids: string[]
          sample_titles: string[]
          earliest_created_at: string
        }[]
      }
      increment_article_view: {
        Args: { p_article_id: string }
        Returns: void
      }
      vote_article: {
        Args: { p_article_id: string; p_helpful: boolean }
        Returns: void
      }
    }
    Enums: Record<string, never>
  }
}
