// HelpFix — Supabase Database Types
//
// Bu dosya elle yazıldı; ileride `supabase gen types typescript` ile
// otomatik üretilenle değiştirilebilir. Şimdilik Faz D (Servis Masası)
// için gereken tabloları ve çekirdek (tenant/kullanıcı) tablolarını
// kapsıyor. Yeni modül eklendikçe buraya yeni tablo tipleri eklenecek.

export type Priority = 'P1' | 'P2' | 'P3' | 'P4'
export type TicketStatus =
  | 'new'
  | 'open'
  | 'in_progress'
  | 'on_hold'
  | 'resolved'
  | 'closed'
  | 'merged'
export type TicketChannel = 'portal' | 'email' | 'chat' | 'phone' | 'teams'
export type UserRole = 'tenant_admin' | 'manager' | 'agent' | 'requester'
export type ProblemStatus =
  | 'investigating'
  | 'root_cause_identified'
  | 'known_error'
  | 'monitoring'
  | 'resolved'
  | 'closed'
export type ChangeType = 'standard' | 'normal' | 'emergency'
export type ChangeStatus =
  | 'draft'
  | 'submitted'
  | 'technical_review'
  | 'cab_review'
  | 'approved'
  | 'scheduled'
  | 'in_progress'
  | 'completed'
  | 'failed'
  | 'closed'
export type ApprovalType = 'technical_review' | 'cab'
export type ApprovalStatus = 'pending' | 'approved' | 'rejected'
export type PirOutcome = 'successful' | 'partial' | 'failed' | 'rolled_back'
export type RequestStatus =
  | 'submitted'
  | 'pending_approval'
  | 'approved'
  | 'in_procurement'
  | 'fulfilled'
  | 'rejected'
export type CiType = 'server' | 'laptop' | 'desktop' | 'network_device' | 'software_license' | 'mobile_device' | 'other'
export type CiStatus = 'active' | 'in_repair' | 'retired' | 'unmanaged'
export type CiRelationshipType = 'depends_on' | 'hosted_on' | 'connected_to'
export type ArticleStatus = 'draft' | 'published' | 'archived'
export type ProjectStatus = 'planning' | 'active' | 'on_hold' | 'completed' | 'cancelled'
export type ProjectHealth = 'green' | 'amber' | 'red'
export type TaskStatus = 'todo' | 'in_progress' | 'done'
export type RiskLevel = 'low' | 'medium' | 'high'
export type RiskStatus = 'open' | 'mitigated' | 'closed'
export type AlertSource = 'datadog' | 'zabbix' | 'prometheus' | 'cloudwatch' | 'manual'
export type AlertSeverity = 'critical' | 'warning' | 'info'
export type AlertStatus = 'firing' | 'acknowledged' | 'resolved'
export type SwapStatus = 'pending' | 'approved' | 'rejected'
export type AutomationTrigger = 'incident_created' | 'problem_created' | 'change_created'
export type AutomationAction = 'assign_to_user' | 'set_priority' | 'assign_by_skill'
export type FishboneCategory = 'people' | 'process' | 'technology' | 'environment'
export type EscalationNotifyRole = 'agent' | 'manager' | 'tenant_admin'
export type OncallNotifyMethod = 'push' | 'call' | 'team_lead'
export type NotificationType = 'ticket_assigned' | 'approval_needed' | 'swap_request' | 'new_comment'
export type SlaTier = 'sla' | 'ola' | 'uc'

export interface Database {
  public: {
    Tables: {
      tenants: {
        Row: {
          id: string
          name: string
          slug: string
          plan: 'starter' | 'growth' | 'enterprise'
          inbound_email: string
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['tenants']['Row'], 'id' | 'created_at'> & {
          id?: string
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['tenants']['Insert']>
        Relationships: []
      }
      user_profiles: {
        Row: {
          id: string
          tenant_id: string
          auth_user_id: string
          full_name: string
          email: string
          role: UserRole
          department_id: string | null
          avatar_initials: string | null
          is_active: boolean
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['user_profiles']['Row'], 'id' | 'created_at'> & {
          id?: string
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['user_profiles']['Insert']>
        Relationships: []
      }
      departments: {
        Row: {
          id: string
          tenant_id: string
          name: string
          manager_id: string | null
        }
        Insert: Omit<Database['public']['Tables']['departments']['Row'], 'id'> & { id?: string }
        Update: Partial<Database['public']['Tables']['departments']['Insert']>
        Relationships: []
      }
      incidents: {
        Row: {
          id: string
          tenant_id: string
          ref: string // e.g. INC-000418, generated by trigger
          title: string
          description: string | null
          priority: Priority
          status: TicketStatus
          channel: TicketChannel
          category: string | null
          requester_id: string
          assignee_id: string | null
          possible_duplicate_of: string | null
          ci_id: string | null
          is_major_incident: boolean
          major_incident_declared_at: string | null
          sla_policy_id: string | null
          sla_due_at: string | null
          csat_score: number | null
          email_message_id: string | null
          custom_fields: Record<string, string>
          created_at: string
          updated_at: string
          resolved_at: string | null
          closed_at: string | null
        }
        Insert: Omit<
          Database['public']['Tables']['incidents']['Row'],
          'id' | 'ref' | 'created_at' | 'updated_at' | 'custom_fields'
        > & {
          id?: string
          ref?: string
          created_at?: string
          updated_at?: string
          custom_fields?: Record<string, string>
        }
        Update: Partial<Database['public']['Tables']['incidents']['Insert']>
        Relationships: []
      }
      ticket_category_fields: {
        Row: {
          id: string
          tenant_id: string
          category_key: string
          field_schema: unknown
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['ticket_category_fields']['Row'], 'id' | 'updated_at'> & {
          id?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['ticket_category_fields']['Insert']>
        Relationships: []
      }
      incident_comments: {
        Row: {
          id: string
          incident_id: string
          author_id: string
          body: string
          is_internal: boolean
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['incident_comments']['Row'], 'id' | 'created_at'> & {
          id?: string
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['incident_comments']['Insert']>
        Relationships: []
      }
      canned_responses: {
        Row: {
          id: string
          tenant_id: string
          title: string
          body: string
          created_by: string | null
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['canned_responses']['Row'], 'id' | 'created_at'> & {
          id?: string
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['canned_responses']['Insert']>
        Relationships: []
      }
      saved_filters: {
        Row: {
          id: string
          tenant_id: string
          user_id: string
          name: string
          filters: Record<string, unknown>
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['saved_filters']['Row'], 'id' | 'created_at'> & {
          id?: string
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['saved_filters']['Insert']>
        Relationships: []
      }
      incident_responders: {
        Row: {
          incident_id: string
          user_id: string
          added_at: string
        }
        Insert: Omit<Database['public']['Tables']['incident_responders']['Row'], 'added_at'> & {
          added_at?: string
        }
        Update: Partial<Database['public']['Tables']['incident_responders']['Insert']>
        Relationships: []
      }
      incident_timeline: {
        Row: {
          id: string
          incident_id: string
          actor_id: string | null
          event_type: string // 'created' | 'assigned' | 'status_changed' | 'ai_action' | ...
          event_data: Record<string, unknown> | null
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['incident_timeline']['Row'], 'id' | 'created_at'> & {
          id?: string
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['incident_timeline']['Insert']>
        Relationships: []
      }
      problems: {
        Row: {
          id: string
          tenant_id: string
          ref: string // e.g. PRB-000031, trigger tarafından üretilir
          title: string
          description: string | null
          status: ProblemStatus
          priority: Priority
          category: string | null
          root_cause: string | null
          is_known_error: boolean
          known_error_workaround: string | null
          owner_id: string | null
          ci_id: string | null
          created_at: string
          updated_at: string
          resolved_at: string | null
        }
        Insert: Omit<
          Database['public']['Tables']['problems']['Row'],
          'id' | 'ref' | 'created_at' | 'updated_at'
        > & {
          id?: string
          ref?: string
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['problems']['Insert']>
        Relationships: []
      }
      problem_incidents: {
        Row: {
          problem_id: string
          incident_id: string
          linked_at: string
        }
        Insert: Omit<Database['public']['Tables']['problem_incidents']['Row'], 'linked_at'> & {
          linked_at?: string
        }
        Update: Partial<Database['public']['Tables']['problem_incidents']['Insert']>
        Relationships: []
      }
      problem_timeline: {
        Row: {
          id: string
          problem_id: string
          actor_id: string | null
          event_type: string
          event_data: Record<string, unknown> | null
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['problem_timeline']['Row'], 'id' | 'created_at'> & {
          id?: string
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['problem_timeline']['Insert']>
        Relationships: []
      }
      changes: {
        Row: {
          id: string
          tenant_id: string
          ref: string // e.g. CHG-000187
          title: string
          description: string | null
          change_type: ChangeType
          status: ChangeStatus
          risk_score: number
          category: string | null
          requester_id: string
          implementer_id: string | null
          scheduled_start: string | null
          scheduled_end: string | null
          actual_start: string | null
          actual_end: string | null
          rollback_plan: string | null
          ci_id: string | null
          pir_outcome: PirOutcome | null
          pir_notes: string | null
          created_at: string
          updated_at: string
          closed_at: string | null
        }
        Insert: Omit<Database['public']['Tables']['changes']['Row'], 'id' | 'ref' | 'created_at' | 'updated_at'> & {
          id?: string
          ref?: string
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['changes']['Insert']>
        Relationships: []
      }
      change_approvals: {
        Row: {
          id: string
          change_id: string
          approval_type: ApprovalType
          approver_id: string | null
          status: ApprovalStatus
          comment: string | null
          decided_at: string | null
        }
        Insert: Omit<Database['public']['Tables']['change_approvals']['Row'], 'id'> & { id?: string }
        Update: Partial<Database['public']['Tables']['change_approvals']['Insert']>
        Relationships: []
      }
      change_timeline: {
        Row: {
          id: string
          change_id: string
          actor_id: string | null
          event_type: string
          event_data: Record<string, unknown> | null
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['change_timeline']['Row'], 'id' | 'created_at'> & {
          id?: string
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['change_timeline']['Insert']>
        Relationships: []
      }
      service_categories: {
        Row: {
          id: string
          tenant_id: string
          name: string
          icon: string | null
          sort_order: number
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['service_categories']['Row'], 'id' | 'created_at'> & {
          id?: string
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['service_categories']['Insert']>
        Relationships: []
      }
      service_catalog_items: {
        Row: {
          id: string
          tenant_id: string
          category_id: string | null
          name: string
          description: string | null
          icon: string | null
          estimated_cost: number | null
          estimated_days: number | null
          requires_approval: boolean
          approval_threshold: number | null
          is_active: boolean
          form_schema: Record<string, unknown> | null
          approval_chain: unknown
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['service_catalog_items']['Row'], 'id' | 'created_at'> & {
          id?: string
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['service_catalog_items']['Insert']>
        Relationships: []
      }
      service_requests: {
        Row: {
          id: string
          tenant_id: string
          ref: string
          catalog_item_id: string
          requester_id: string
          requested_for_id: string | null
          status: RequestStatus
          notes: string | null
          approver_id: string | null
          approval_comment: string | null
          form_data: Record<string, unknown> | null
          bundle_request_batch_id: string | null
          created_at: string
          updated_at: string
          fulfilled_at: string | null
        }
        Insert: Omit<
          Database['public']['Tables']['service_requests']['Row'],
          'id' | 'ref' | 'created_at' | 'updated_at'
        > & {
          id?: string
          ref?: string
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['service_requests']['Insert']>
        Relationships: []
      }
      vendors: {
        Row: {
          id: string
          tenant_id: string
          name: string
          contact_name: string | null
          contact_email: string | null
          contact_phone: string | null
          notes: string | null
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['vendors']['Row'], 'id' | 'created_at'> & {
          id?: string
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['vendors']['Insert']>
        Relationships: []
      }
      contracts: {
        Row: {
          id: string
          tenant_id: string
          ref: string
          vendor_id: string | null
          name: string
          contract_type: 'service' | 'license' | 'maintenance' | 'lease' | 'other'
          start_date: string
          end_date: string
          cost: number | null
          currency: string
          auto_renew: boolean
          renewal_reminder_days: number
          notes: string | null
          owner_id: string | null
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['contracts']['Row'], 'id' | 'ref' | 'created_at'> & {
          id?: string
          ref?: string
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['contracts']['Insert']>
        Relationships: []
      }
      contract_assets: {
        Row: { contract_id: string; ci_id: string }
        Insert: { contract_id: string; ci_id: string }
        Update: Partial<{ contract_id: string; ci_id: string }>
        Relationships: []
      }
      purchase_orders: {
        Row: {
          id: string
          tenant_id: string
          ref: string
          vendor_id: string | null
          title: string
          status: 'draft' | 'pending_approval' | 'approved' | 'ordered' | 'received' | 'cancelled'
          total_cost: number
          currency: string
          requested_by: string
          approved_by: string | null
          service_request_id: string | null
          expected_delivery_date: string | null
          ordered_at: string | null
          received_at: string | null
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['purchase_orders']['Row'], 'id' | 'ref' | 'created_at' | 'updated_at'> & {
          id?: string
          ref?: string
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['purchase_orders']['Insert']>
        Relationships: []
      }
      purchase_order_items: {
        Row: {
          id: string
          po_id: string
          description: string
          quantity: number
          unit_cost: number
          ci_id: string | null
        }
        Insert: Omit<Database['public']['Tables']['purchase_order_items']['Row'], 'id'> & { id?: string }
        Update: Partial<Database['public']['Tables']['purchase_order_items']['Insert']>
        Relationships: []
      }
      request_approvals: {
        Row: {
          id: string
          request_id: string
          stage: number
          approver_type: 'department_manager' | 'tenant_admin' | 'specific_user'
          approver_id: string | null
          status: 'pending' | 'approved' | 'rejected'
          comment: string | null
          decided_at: string | null
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['request_approvals']['Row'], 'id' | 'created_at' | 'status' | 'comment' | 'decided_at'> & {
          id?: string
          created_at?: string
          status?: 'pending' | 'approved' | 'rejected'
          comment?: string | null
          decided_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['request_approvals']['Insert']>
        Relationships: []
      }
      configuration_items: {
        Row: {
          id: string
          tenant_id: string
          tag: string
          name: string
          ci_type: CiType
          status: CiStatus
          serial_number: string | null
          assigned_user_id: string | null
          vendor: string | null
          cost: number | null
          purchase_date: string | null
          warranty_expiry: string | null
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: Omit<
          Database['public']['Tables']['configuration_items']['Row'],
          'id' | 'tag' | 'created_at' | 'updated_at'
        > & {
          id?: string
          tag?: string
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['configuration_items']['Insert']>
        Relationships: []
      }
      ci_relationships: {
        Row: {
          id: string
          tenant_id: string
          source_ci_id: string
          target_ci_id: string
          relationship_type: CiRelationshipType
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['ci_relationships']['Row'], 'id' | 'created_at'> & {
          id?: string
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['ci_relationships']['Insert']>
        Relationships: []
      }
      knowledge_articles: {
        Row: {
          id: string
          tenant_id: string
          title: string
          slug: string
          content: string
          category: string | null
          status: ArticleStatus
          author_id: string
          view_count: number
          helpful_count: number
          unhelpful_count: number
          decision_tree: Record<string, unknown> | null
          created_at: string
          updated_at: string
          published_at: string | null
        }
        Insert: Omit<
          Database['public']['Tables']['knowledge_articles']['Row'],
          'id' | 'slug' | 'created_at' | 'updated_at' | 'view_count' | 'helpful_count' | 'unhelpful_count'
        > & {
          id?: string
          slug?: string
          created_at?: string
          updated_at?: string
          view_count?: number
          helpful_count?: number
          unhelpful_count?: number
        }
        Update: Partial<Database['public']['Tables']['knowledge_articles']['Insert']>
        Relationships: []
      }
      sla_policies: {
        Row: {
          id: string
          tenant_id: string
          name: string
          priority: Priority
          category: string | null
          response_time_minutes: number
          resolution_time_minutes: number
          escalation_warning_percent: number
          business_hours_only: boolean
          tier: SlaTier
          is_active: boolean
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['sla_policies']['Row'], 'id' | 'created_at'> & {
          id?: string
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['sla_policies']['Insert']>
        Relationships: []
      }
      business_hours: {
        Row: {
          id: string
          tenant_id: string
          day_of_week: number
          start_time: string
          end_time: string
        }
        Insert: Omit<Database['public']['Tables']['business_hours']['Row'], 'id'> & {
          id?: string
        }
        Update: Partial<Database['public']['Tables']['business_hours']['Insert']>
        Relationships: []
      }
      tenant_holidays: {
        Row: {
          id: string
          tenant_id: string
          holiday_date: string
          name: string
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['tenant_holidays']['Row'], 'id' | 'created_at'> & {
          id?: string
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['tenant_holidays']['Insert']>
        Relationships: []
      }
      ai_quota: {
        Row: {
          tenant_id: string
          monthly_limit: number
          updated_at: string
        }
        Insert: Partial<Database['public']['Tables']['ai_quota']['Row']> & { tenant_id: string }
        Update: Partial<Database['public']['Tables']['ai_quota']['Insert']>
        Relationships: []
      }
      ai_usage_log: {
        Row: {
          id: string
          tenant_id: string
          user_id: string | null
          action: string
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['ai_usage_log']['Row'], 'id' | 'created_at'> & {
          id?: string
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['ai_usage_log']['Insert']>
        Relationships: []
      }
      incident_links: {
        Row: {
          id: string
          tenant_id: string
          incident_id: string
          linked_incident_id: string
          link_type: 'related_to' | 'duplicate_of' | 'caused_by'
          created_by: string | null
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['incident_links']['Row'], 'id' | 'created_at'> & {
          id?: string
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['incident_links']['Insert']>
        Relationships: []
      }
      projects: {
        Row: {
          id: string
          tenant_id: string
          name: string
          description: string | null
          status: ProjectStatus
          health: ProjectHealth
          owner_id: string | null
          start_date: string | null
          end_date: string | null
          budget: number | null
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['projects']['Row'], 'id' | 'created_at' | 'updated_at'> & {
          id?: string
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['projects']['Insert']>
        Relationships: []
      }
      project_tasks: {
        Row: {
          id: string
          tenant_id: string
          project_id: string
          title: string
          status: TaskStatus
          assignee_id: string | null
          due_date: string | null
          start_date: string | null
          sort_order: number
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['project_tasks']['Row'], 'id' | 'created_at'> & {
          id?: string
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['project_tasks']['Insert']>
        Relationships: []
      }
      project_risks: {
        Row: {
          id: string
          tenant_id: string
          project_id: string
          title: string
          description: string | null
          impact: RiskLevel
          likelihood: RiskLevel
          status: RiskStatus
          owner_id: string | null
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['project_risks']['Row'], 'id' | 'created_at'> & {
          id?: string
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['project_risks']['Insert']>
        Relationships: []
      }
      monitoring_alerts: {
        Row: {
          id: string
          tenant_id: string
          source: AlertSource
          title: string
          description: string | null
          severity: AlertSeverity
          status: AlertStatus
          ci_id: string | null
          incident_id: string | null
          acknowledged_by: string | null
          fired_at: string
          acknowledged_at: string | null
          resolved_at: string | null
        }
        Insert: Omit<Database['public']['Tables']['monitoring_alerts']['Row'], 'id' | 'fired_at'> & {
          id?: string
          fired_at?: string
        }
        Update: Partial<Database['public']['Tables']['monitoring_alerts']['Insert']>
        Relationships: []
      }
      oncall_schedules: {
        Row: {
          id: string
          tenant_id: string
          name: string
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['oncall_schedules']['Row'], 'id' | 'created_at'> & {
          id?: string
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['oncall_schedules']['Insert']>
        Relationships: []
      }
      oncall_shifts: {
        Row: {
          id: string
          tenant_id: string
          schedule_id: string
          user_id: string
          start_time: string
          end_time: string
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['oncall_shifts']['Row'], 'id' | 'created_at'> & {
          id?: string
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['oncall_shifts']['Insert']>
        Relationships: []
      }
      oncall_swap_requests: {
        Row: {
          id: string
          tenant_id: string
          shift_id: string
          requested_by: string
          requested_to: string
          status: SwapStatus
          created_at: string
          decided_at: string | null
        }
        Insert: Omit<Database['public']['Tables']['oncall_swap_requests']['Row'], 'id' | 'created_at'> & {
          id?: string
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['oncall_swap_requests']['Insert']>
        Relationships: []
      }
      user_skills: {
        Row: {
          id: string
          tenant_id: string
          user_id: string
          category_label: string
          proficiency: number
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['user_skills']['Row'], 'id' | 'created_at'> & {
          id?: string
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['user_skills']['Insert']>
        Relationships: []
      }
      automation_rules: {
        Row: {
          id: string
          tenant_id: string
          name: string
          trigger_type: AutomationTrigger
          condition_category: string | null
          condition_priority: Priority | null
          action_type: AutomationAction
          action_assignee_id: string | null
          action_priority: Priority | null
          is_active: boolean
          execution_count: number
          created_at: string
        }
        Insert: Omit<
          Database['public']['Tables']['automation_rules']['Row'],
          'id' | 'created_at' | 'execution_count'
        > & {
          id?: string
          created_at?: string
          execution_count?: number
        }
        Update: Partial<Database['public']['Tables']['automation_rules']['Insert']>
        Relationships: []
      }
      tenant_feature_flags: {
        Row: {
          tenant_id: string
          module_code: string
          is_enabled: boolean
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['tenant_feature_flags']['Row'], 'updated_at'> & {
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['tenant_feature_flags']['Insert']>
        Relationships: []
      }
      problem_fishbone_causes: {
        Row: {
          id: string
          tenant_id: string
          problem_id: string
          category: FishboneCategory
          description: string
          is_confirmed_root_cause: boolean
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['problem_fishbone_causes']['Row'], 'id' | 'created_at'> & {
          id?: string
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['problem_fishbone_causes']['Insert']>
        Relationships: []
      }
      change_freeze_windows: {
        Row: {
          id: string
          tenant_id: string
          name: string
          start_date: string
          end_date: string
          reason: string | null
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['change_freeze_windows']['Row'], 'id' | 'created_at'> & {
          id?: string
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['change_freeze_windows']['Insert']>
        Relationships: []
      }
      service_bundles: {
        Row: {
          id: string
          tenant_id: string
          name: string
          description: string | null
          is_active: boolean
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['service_bundles']['Row'], 'id' | 'created_at'> & {
          id?: string
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['service_bundles']['Insert']>
        Relationships: []
      }
      service_bundle_items: {
        Row: {
          bundle_id: string
          catalog_item_id: string
        }
        Insert: Database['public']['Tables']['service_bundle_items']['Row']
        Update: Partial<Database['public']['Tables']['service_bundle_items']['Insert']>
        Relationships: []
      }
      sla_escalation_levels: {
        Row: {
          id: string
          tenant_id: string
          sla_policy_id: string
          level: number
          trigger_percent: number
          notify_role: EscalationNotifyRole
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['sla_escalation_levels']['Row'], 'id' | 'created_at'> & {
          id?: string
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['sla_escalation_levels']['Insert']>
        Relationships: []
      }
      dashboard_widgets: {
        Row: {
          id: string
          tenant_id: string
          user_id: string
          widget_type: string
          sort_order: number
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['dashboard_widgets']['Row'], 'id' | 'created_at'> & {
          id?: string
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['dashboard_widgets']['Insert']>
        Relationships: []
      }
      oncall_escalation_steps: {
        Row: {
          id: string
          tenant_id: string
          schedule_id: string
          step_order: number
          delay_minutes: number
          notify_method: OncallNotifyMethod
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['oncall_escalation_steps']['Row'], 'id' | 'created_at'> & {
          id?: string
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['oncall_escalation_steps']['Insert']>
        Relationships: []
      }
      change_templates: {
        Row: {
          id: string
          tenant_id: string
          name: string
          description: string | null
          category: string | null
          default_risk_score: number
          default_rollback_plan: string | null
          is_active: boolean
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['change_templates']['Row'], 'id' | 'created_at'> & {
          id?: string
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['change_templates']['Insert']>
        Relationships: []
      }
      notifications: {
        Row: {
          id: string
          tenant_id: string
          user_id: string
          type: NotificationType
          title: string
          body: string | null
          link: string | null
          is_read: boolean
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['notifications']['Row'], 'id' | 'created_at'> & {
          id?: string
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['notifications']['Insert']>
        Relationships: []
      }
      monitoring_runbooks: {
        Row: {
          id: string
          tenant_id: string
          trigger_keyword: string
          title: string
          steps: string
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['monitoring_runbooks']['Row'], 'id' | 'created_at'> & {
          id?: string
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['monitoring_runbooks']['Insert']>
        Relationships: []
      }
      audit_log: {
        Row: {
          id: string
          tenant_id: string
          actor_id: string | null
          action: string
          target_type: string
          target_label: string | null
          details: Record<string, unknown> | null
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['audit_log']['Row'], 'id' | 'created_at'> & {
          id?: string
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['audit_log']['Insert']>
        Relationships: []
      }
      kb_search_log: {
        Row: {
          id: string
          tenant_id: string
          query: string
          result_count: number
          searched_by: string | null
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['kb_search_log']['Row'], 'id' | 'created_at'> & {
          id?: string
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['kb_search_log']['Insert']>
        Relationships: []
      }
    }
    Views: Record<string, never>
    Functions: {
      get_incident_cluster_candidates: {
        Args: { p_tenant_id: string }
        Returns: {
          category: string
          incident_count: number
          sample_incident_ids: string[]
          sample_titles: string[]
          earliest_created_at: string
        }[]
      }
      increment_article_view: {
        Args: { p_article_id: string }
        Returns: void
      }
      vote_article: {
        Args: { p_article_id: string; p_helpful: boolean }
        Returns: void
      }
      get_weekly_incident_trend: {
        Args: { p_tenant_id: string }
        Returns: { week_start: string; created_count: number; resolved_count: number }[]
      }
      get_sla_compliance: {
        Args: { p_tenant_id: string }
        Returns: { total_resolved: number; breached_count: number; compliance_percent: number }[]
      }
      get_change_success_rate: {
        Args: { p_tenant_id: string }
        Returns: { total_closed: number; successful_count: number; success_percent: number }[]
      }
      get_daily_alert_volume: {
        Args: { p_tenant_id: string }
        Returns: { day: string; alert_count: number; critical_count: number }[]
      }
      get_mtta_by_source: {
        Args: { p_tenant_id: string }
        Returns: { source: string; avg_minutes: number; alert_count: number }[]
      }
      get_oncall_fairness: {
        Args: { p_tenant_id: string; p_schedule_id: string }
        Returns: { user_id: string; full_name: string; shift_count: number; total_hours: number }[]
      }
      get_channel_distribution: {
        Args: { p_tenant_id: string }
        Returns: { channel: string; ticket_count: number }[]
      }
      get_ai_usage_current_month: {
        Args: { p_tenant_id: string }
        Returns: { action: string; call_count: number }[]
      }
      search_kb_articles: {
        Args: { p_tenant_id: string; p_query: string; p_limit?: number }
        Returns: { id: string; title: string; slug: string; category: string | null; rank: number }[]
      }
      get_technician_csat_leaderboard: {
        Args: { p_tenant_id: string }
        Returns: { technician_id: string; full_name: string; avg_csat: number; ticket_count: number }[]
      }
      get_root_cause_category_breakdown: {
        Args: { p_tenant_id: string }
        Returns: { category: string; confirmed_count: number }[]
      }
      get_weekly_problem_trend: {
        Args: { p_tenant_id: string }
        Returns: { week_start: string; created_count: number; resolved_count: number }[]
      }
      get_change_risk_distribution: {
        Args: { p_tenant_id: string }
        Returns: { bucket: string; change_count: number }[]
      }
      get_approval_bottleneck: {
        Args: { p_tenant_id: string }
        Returns: { approval_type: string; avg_wait_hours: number; decided_count: number }[]
      }
      get_weekly_change_success_trend: {
        Args: { p_tenant_id: string }
        Returns: { week_start: string; successful_count: number; failed_count: number }[]
      }
      get_duplicate_ci_names: {
        Args: { p_tenant_id: string }
        Returns: { name: string; ci_count: number; ci_ids: string[] }[]
      }
      get_kb_gap_analysis: {
        Args: { p_tenant_id: string }
        Returns: { query: string; search_count: number; last_searched: string }[]
      }
      get_service_desk_daily_volume: {
        Args: { p_tenant_id: string }
        Returns: { day: string; created_count: number; resolved_count: number }[]
      }
    }
    Enums: Record<string, never>
  }
}
